#import "@local/notes:0.1.0": *

= We Are What We Learn

I would like to extend a warm welcome to President Barack Obama.

Hello everybody! Thank you! Thank you! Thank you everybody. All right, everyone go ahead and have a seat. How's everybody doing today? How about Tim Spicer?

I'm here with students at Wakefiled High School in Allington, Virginia. And we've got students tuning in from all across America from Kindgaton to twelfth grade. And I am just glad that all could join us today. And I want to thank Wakefield for being such an outstanding host. Give yourselves a big round of applause.

I know that, for many of you, today is the first day of school. And for those of you in kindergaten or starting middle or hight school, it's your first day in a new school, so it's understandable if you're a little nervous. I imagine there are some seniors out there who are feeling pretty good right now -- with just more year to go. And no matter what grade you're in, some of you are probably wishing you were still in summer, and you could've stayed in bed just a bit little longer this morning. I know that feeling. When I was young, my family lived overseas. I lived in Indonesia for a few years. And my mother, she didn't have the money to sent me to where all the American kids went to school. But she thought it was important for me to keep up with an American education. So she decided to teach me extra lessons herself, Monday to Friday. But because she had to go to work, the only time she could do it was at 4:30 in the morning. Now, as you might imagine, I wasn't too happy about getting up that early. A lot of times, I'd fall asleep right there at the kitchen table. But whenver I'd complain, my mother would just give me one of those looks, she'd say,"This is no picnic for me either, buster." 

So I know some of you are still adjusting to being back at school. But I'm here today because I have something important to discuss with you. I'm here with you because I want to talk with you about your education, and what's expected of all of you in this new school year. Now, I've given a lot of speeches about education, and I've talked about responsibility a lot. I've talked about teachers' responsibility for inspiring students and pushing you to learn. I've talked about your parents' responsibility for making sure you stay on track and you get your homework done, and don't spend every waking hour in front of the TV or with the Xbox. I've talked a lot about your government's responsibility for setting high standards, and supporting teachers and principals, and *turning around the schools* that are't working, where students are't getting the opportunities they deserve. But at the end of the day, we can have the most dedicated teachers, most important parents, the best schools in the world, and none of it will make a differencit, none of it will matter, unless all of you fulfill your responsibility, unless you show up to those schools, unless you pay attention to those teachers, unless you listen to your parents and grandparents and other adults and put in the hard work it takes to succeed. 

That's what I want to focus on today: the responsibility each of you has for your education.
I want to start with the responsibility you have to yourself. Every single one of you has something you are good at. Every sinele one of you has something to offer. And you have a responsibility to yourself to discover what that is. That's the opportunity an education can provide. May be you could be a great writer, maybe even good enough to write a book or articles in a newspaper, but you might not know it until you write that English paper, that English class paper that's assigned to you. Maybe you could be an innovator or an inventor, maybe even good enough to come up with the next iPhone or the new medicine or vaccine. But you might not know it until you do your project for your science class. Maybe you could be a mayor or a senator or a Supreme Court justice. But you might not know that until you join student government or the debate team. And no matter what you want to do with your life, I guarantee that you'll need education to do it. You want to be a doctor, a teacher or a police officer. You want to be a nurse, an architect, a lawyer or a member of our military. You're gonna need a good education for every single one of those careers. You can not drop out of school and just drop into a good job. You've got to train for it and work for it and learn for it. And this isn't just important for your own life and your own future. _What you make of your education will decide nothing less than the future of this country._ The future of America depends on you. _What you're learning in school today will determine whether we as a nation can meet out greatest chanllenges in the future._

#pagebreak()
